#ifndef CPU_EXCEPTIONSTACKFRAMES_H_INC
#define CPU_EXCEPTIONSTACKFRAMES_H_INC
/*
	Declarations of structs representing various stack frames generated by the MC68010 during
	exception processing.

	Part of the as-yet-unnamed MC68010 operating system


	(c) Stuart Wallace, December 2011.
*/

#include "include/types.h"


/*
	MC68010 address/bus-error exception stack frame
*/
struct mc68010_address_exc_frame
{
	const u16 sr;
	const u32 pc;
	const u16 vector_offset;
	const u16 special_status_word;
	const u32 fault_addr;
	const u16 unused_reserved_1;
	const u16 data_output_buffer;
	const u16 unused_reserved_2;
	const u16 data_input_buffer;
	const u16 unused_reserved_3;
	const u16 instr_output_buffer;
	const u16 version_number;
	const u16 internal_information[15];
} __attribute__((packed));


/*
	MC68010 group 1/2 exception stack frame
*/
struct mc68010_exc_frame
{
    const u32 dummy;
	const u16 sr;
	const u32 pc;
	const u16 vector_offset;
} __attribute__((packed));

#endif

